name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - v4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Quartz
        run: npm run docs
      
      - name: Deploy to Hostinger
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -e "set ftp:ssl-allow false; set ssl:verify-certificate no; open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ftp://${{ secrets.FTP_HOST }}; mirror -R ./public ./public_html; quit"